apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dtrq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dtrq
    app.kubernetes.io/part-of: byoc-app-uaqb
  name: dtrq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: dtrq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: dtrq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-tqvq-tenant/byoc-app-uaqb/dtrq@sha256:3adbf34dfdda6feceb3ba9a24a9f218112d5a20d43704a8cce83ea360831334e
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
